Feature/ubi 244 gke deployment
Ubivius/telemetry-loki pull request #1
Opened 2021-02-21 19:03 UTC by MaximeStOnge

#### What changes does this PR contain?
Resources override and Readme

#### Which JIRA ticket ID's are associated with this PR?
UBI-244

#### Additional comments and information

2021-02-21 20:34 UTC, ysma500 requested changes

2021-02-21 20:34 UTC, ysma500 commented on chart/values.yaml
> +  limits:
Req first

2021-02-21 20:34 UTC, ysma500 commented on chart/values.yaml
> +    limits:
Req first

2021-02-21 20:34 UTC, ysma500 commented on chart/values.yaml
> +      memory: 128Mi
New line EOF

2021-02-21 23:06 UTC, ysma500 approved these changes

2021-02-22 23:13 UTC, ArcticWalrus approved these changes

2021-02-22 23:13 UTC, merged